# Generated by Django 4.2.2 on 2024-04-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
